### ISSUE TITLE
Extra newline in git output

### ISSUE THREAD

**Issue by iuliand-db** [databricks/devbox#9]
When running git commands through the Git proxy there's an extra newline in the output.

```
$ git branch
  CJ-25007
  issue/PLAT-16767-error-msgs
  issue/quill-static-analysis-bug
  master
  pr/56970
* upgrade/devbox-script
  upgrade/scala-2.12.11
  upgrade/sjsonnet

```

**Comment by iuliand-db** [comment]
It seems that [print without a newline in python is a big thing](https://www.geeksforgeeks.org/print-without-newline-python/) .. :)

So we need to find a Python 2.7-compatible way to print without the automatic newline.

**Comment by lihaoyi-databricks** [comment]
fixed by https://github.com/databricks/devbox/pull/10
